using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

//examine the buggy Controller, the errors generated by each of those methods are different and 
//incosistent, we want to have consistent errors for angular to handle the exceptions, we will see more of
//that in the angular side
namespace API.Errors
{
    public class ApiResonse
    {
        public ApiResonse(int statusCode, string message = null)
        {
            StatusCode = statusCode;
            Message = message ?? GetDefaultMessageForStatusCode(statusCode);
        }

        public int StatusCode { get; set; }
        public string Message { get; set; }
        private string GetDefaultMessageForStatusCode(int statusCode)
        {
            return statusCode switch
            {
                400 => "A bad request, you have made",
                401 => "You are not authenticated",
                404 => "Resource found, it was not",
                500 => "Errors are the darker side, is it?",
                _ => null
            };
        }
        
    }
}